import type { Metadata } from "next";
import "./globals.css";
import { ebGaramond, inter, raleway, bebasNeue } from "./fonts";
export const metadata: Metadata = {
  title: "Blossom Coffee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.variable} ${inter.variable} ${raleway.variable} ${bebasNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
